package it.polimi.ingsw.lim.common.enums;

public enum ActionType
{
	COUNCIL_PALACE,
	GET_CARD,
	HARVEST_START,
	LEADER_ACTIVATION,
	LEADER_DISCARD,
	LEADER_PLAY,
	MARKET,
	PRODUCTION_START,
	PRODUCTION_TRADE
}
