package it.polimi.ingsw.lim.common.enums;

public enum ActionType
{
	CHOOSE_LORENZO_DE_MEDICI_LEADER,
	CHOOSE_REWARD_COUNCIL_PRIVILEGE,
	CHOOSE_REWARD_HARVEST,
	CHOOSE_REWARD_PICK_DEVELOPMENT_CARD,
	CHOOSE_REWARD_PRODUCTION_START,
	CHOOSE_REWARD_TEMPORARY_MODIFIER,
	COUNCIL_PALACE,
	HARVEST,
	LEADER_ACTIVATE,
	LEADER_DISCARD,
	LEADER_PLAY,
	MARKET,
	PASS_TURN,
	PICK_DEVELOPMENT_CARD,
	PRODUCTION_START,
	PRODUCTION_TRADE,
	REFUSE_REWARD,
	SHOW_CARDS,
	SHOW_LEADERS,
	LEADER_ACTION
}
