package it.polimi.ingsw.lim.common.enums;

public enum ActionType
{
	CHOOSE_LORENZO_DE_MEDICI_LEADER,
	CHOOSE_REWARD_COUNCIL_PRIVILEGE,
	CHOOSE_REWARD_GET_DEVELOPMENT_CARD,
	CHOOSE_REWARD_HARVEST,
	CHOOSE_REWARD_PRODUCTION,
	CHOOSE_REWARD_TEMPORARY_MODIFIER,
	COUNCIL_PALACE,
	GET_DEVELOPMENT_CARD,
	HARVEST_START,
	LEADER_ACTIVATION,
	LEADER_DISCARD,
	LEADER_PLAY,
	MARKET,
	PASS_TURN,
	PRODUCTION_START,
	PRODUCTION_TRADE,
	REFUSE_REWARD
}
