package it.polimi.ingsw.lim.common.enums;

public enum PacketType
{
	AUTHENTICATION_CONFIRMATION,
	AUTHENTICATION_FAILURE,
	CHAT_MESSAGE,
	DISCONNECTION_ACKNOWLEDGEMENT,
	DISCONNECTION_LOG_MESSAGE,
	GAME_PERSONAL_BONUS_TILE_CHOICE_REQUEST,
	GAME_PERSONAL_BONUS_TILE_CHOICE_OTHER,
	GAME_PERSONAL_BONUS_TILE_CHOSEN,
	GAME_PERSONAL_BONUS_TILE_PLAYER_CHOICE,
	GAME_STARTED,
	GAME_UPDATE,
	GAME_UPDATE_EXPECTED_ACTION,
	GAME_UPDATE_OTHER_TURN,
	HEARTBEAT,
	LOG_MESSAGE,
	LOGIN,
	REGISTRATION,
	ROOM_ENTRY_OTHER,
	ROOM_EXIT_OTHER,
	ROOM_TIMER,
	ROOM_TIMER_REQUEST,
}
