package it.polimi.ingsw.lim.client.enums;

public enum CLIStatus
{
	NONE,
	INTERFACE_CHOICE,
	CONNECTION,
	AUTHENTICATION,
	PERSONAL_BONUS_TILE_CHOICE,
	LEADER_CARDS_CHOICE,
	EXCOMMUNICATION_CHOICE,
	AVAILABLE_ACTIONS,
	COUNCIL_PALACE,
	HARVEST,
	PRODUCTION_START,
	MARKET,
	PICK_DEVELOPMENT_CARD,
	LEADER_ACTIVATE,
	LEADER_DISCARD,
	LEADER_PLAY,
	SHOW_BOARD_DEVELOPMENT_CARDS,
	SHOW_OWN_BOARD,
	SHOW_OWN_LEADER_CARDS,
	SHOW_OTHER_LEADER_CARDS,
	CHOOSE_LORENZO_DE_MEDICI_LEADER,
	CHOOSE_REWARD_COUNCIL_PRIVILEGE,
	CHOOSE_REWARD_HARVEST,
	CHOOSE_REWARD_PICK_DEVELOPMENT_CARD,
	CHOOSE_REWARD_PRODUCTION_START,
	CHOOSE_REWARD_TEMPORARY_MODIFIER,
	PRODUCTION_TRADE,
	GAME_ENDED
}
