package it.polimi.ingsw.lim.client.enums;

public enum CLIStatus
{
	NONE,
	INTERFACE_CHOICE,
	CONNECTION,
	AUTHENTICATION,
	PERSONAL_BONUS_TILE_CHOICE,
	LEADER_CARDS_CHOICE,
	AVAILABLE_ACTIONS,
	SHOW_CARDS,
	SHOW_LEADERS,
	COUNCIL_PALACE,
	HARVEST,
	PRODUCTION_START,
	MARKET,
	PICK_DEVELOPMENT_CARD,
	LEADER_ACTIVATE,
	LEADER_DISCARD,
	LEADER_PLAY
}
